Feature/ab#898 preselect classification
starwit/react-image-annotate pull request #6
Opened 2023-10-30 12:40 UTC by flostyl3

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-30 14:34 UTC, flonix8 commented
It might be a good idea, to change the DemoSite such that one of the demo classes is automatically selected.
(In case we're still maintaining that demo. Otherwise nevermind)

2023-10-31 12:48 UTC, flonix8 commented
Also, we might want to add the new property to the list of available props in `README.md`

2023-11-06 13:16 UTC, flonix8 requested changes

2023-11-06 13:16 UTC, flonix8 commented on src/ClassSelectionMenu/index.js
> +    if(preselectCls!=null && selectedCls==null){
Some more whitespace would be nice :)

2023-11-06 13:16 UTC, flonix8 commented on src/MainLayout/index.js
> +              (acc, p, i) => (((acc[p] = args[i]), acc)), {})
I have absolutely no idea what this does :sweat_smile: 
Are you sure, the parenthesis change anything?

2023-11-06 13:18 UTC, flonix8 commented
I had some more things that I wanted you to check (not sure if they actually have to be changed)

> It might be a good idea, to change the DemoSite such that one of the demo classes is automatically selected. (In case we're still maintaining that demo. Otherwise nevermind)

Please also have a look at my previous comment.

2023-11-08 11:06 UTC, flostyl3 commented
> It might be a good idea, to change the DemoSite such that one of the demo classes is automatically selected. (In case we're still maintaining that demo. Otherwise nevermind)

Good suggest. i added this

2023-11-08 11:07 UTC, flostyl3 commented
> Also, we might want to add the new property to the list of available props in `README.md`

fixed it

2023-11-08 11:17 UTC, flostyl3 commented on src/MainLayout/index.js
> +              (acc, p, i) => (((acc[p] = args[i]), acc)), {})
there where compiler Warnings about this so I fixed it. I don't know what the difference is ether

2023-11-08 15:46 UTC, flonix8 requested changes

2023-11-08 15:46 UTC, flonix8 commented on src/ClassSelectionMenu/index.jsx
> +  useEffect(() => {
I have now found out why this useEffect() call had been removed in the meantime (and we readded it earlier during the merge).
This is part of the problematic keyboard shortcuts, that Anett removed. So you have to remove all key related parts and check if the implementation still works.

2023-11-13 09:46 UTC, merged